# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'client-core (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.5'
  pod 'FeedKit', '~> 9.0'
  # Pods for client-core (iOS)

end

target 'client-core (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.5'
  pod 'FeedKit', '~> 9.0'
  # Pods for client-core (macOS)

end
